// pm-skills-tools — the pm-claude-skills library (743 skills) as agent tools.
// Generated by scripts/build-tools-exports.mjs — do not edit by hand.
//
//   import { pick, search, toOpenAI, toVercelAI } from 'pm-skills-tools';
//   const tools = pick(['prd_template', 'meeting_notes']);          // never ship all 743 to one context
//   const openaiTools = toOpenAI(tools);                            // OpenAI / any JSON-schema caller
//   const aiSdkTools  = toVercelAI(tools);                          // Vercel AI SDK ({ [name]: {description, parameters, execute} })
//
// Executing a tool returns the skill's full instructions + the input for YOUR
// model to carry out (the get_skill pattern): no extra key, no second vendor.
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const INDEX = JSON.parse(readFileSync(join(here, 'index.json'), 'utf8'));
const body = (name) => readFileSync(join(here, 'instructions', name + '.md'), 'utf8');

export const names = INDEX.map((t) => t.name);
export function get(name) {
  const t = INDEX.find((x) => x.name === name || x.skill === name);
  if (!t) throw new Error('Unknown skill tool: ' + name);
  return { ...t, instructions: body(t.skill) };
}
export function pick(list) { return list.map(get); }
export function search(query, limit = 5) {
  const terms = String(query).toLowerCase().split(/\s+/).filter(Boolean);
  return INDEX.map((t) => {
    const hay = (t.name + ' ' + t.description).toLowerCase();
    let score = 0;
    for (const w of terms) if (hay.includes(w)) score += t.name.includes(w) ? 2 : 1;
    return { t, score };
  }).filter((x) => x.score > 0).sort((a, b) => b.score - a.score).slice(0, limit).map((x) => get(x.t.name));
}
const directive = (t, input) =>
  'You now have the following professional skill loaded. Execute it on the input and produce the complete artifact.\n\n' +
  t.instructions + '\n\n---\nINPUT:\n' + input;

export function toOpenAI(tools) {
  return tools.map((t) => ({ type: 'function', function: { name: t.name, description: t.description,
    parameters: { type: 'object', properties: { input: { type: 'string', description: "The user's raw input for this skill." } }, required: ['input'] } } }));
}
export function executeOpenAI(tools, name, args) {
  const t = tools.find((x) => x.name === name); if (!t) throw new Error('Unknown tool: ' + name);
  return directive(t, (typeof args === 'string' ? JSON.parse(args) : args).input || '');
}
export function toVercelAI(tools) {
  const out = {};
  for (const t of tools) out[t.name] = {
    description: t.description,
    parameters: { type: 'object', properties: { input: { type: 'string' } }, required: ['input'] },
    execute: async ({ input }) => directive(t, input || ''),
  };
  return out;
}
