#!/usr/bin/env node
// Scheduled reports — close the loop by having a skill run itself on a cadence
// and deliver the result, instead of you remembering to open the playground
// every Monday. Reads config/scheduled-reports.json, figures out which reports
// are DUE today, runs each due skill once against your inputs, and writes the
// output to docs/reports/scheduled/. Delivery beyond "commit" (email, Slack) is
// wired in the workflow — this script produces the artifact.
//
//   node scripts/scheduled-report.mjs              # run whatever is due today
//   node scripts/scheduled-report.mjs --force      # run all, ignore the schedule
//   node scripts/scheduled-report.mjs --id weekly-portfolio-pulse
//   node scripts/scheduled-report.mjs --dry-run    # no API call; show what's due
//
// Needs ANTHROPIC_API_KEY (unless --dry-run). Exit 0 ok · 1 error.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { complete } from '../bin/lib/anthropic.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const arg = (n, d) => { const i = process.argv.indexOf('--' + n); return i >= 0 && process.argv[i + 1] && !process.argv[i + 1].startsWith('--') ? process.argv[i + 1] : d; };
const has = (n) => process.argv.includes('--' + n);

const cfgPath = join(root, 'config', 'scheduled-reports.json');
if (!existsSync(cfgPath)) { console.error('No config/scheduled-reports.json'); process.exit(1); }
const cfg = JSON.parse(readFileSync(cfgPath, 'utf8'));
const skills = JSON.parse(readFileSync(join(root, 'web', 'skills.json'), 'utf8')).skills || [];
const skillOf = (name) => skills.find((s) => s.name === name);

// Is a report due on `date`? weekly/biweekly use day-of-week; monthly uses
// day-of-month. biweekly fires on matching weeks (ISO week parity).
function isDue(r, date) {
  const cadence = r.cadence || 'weekly';
  if (cadence === 'monthly') return date.getUTCDate() === (r.day || 1);
  if (date.getUTCDay() !== (r.day == null ? 1 : r.day)) return false;
  if (cadence === 'biweekly') {
    const week = Math.floor((Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()) / 86400000 + 3) / 7);
    return week % 2 === 0;
  }
  return true; // weekly
}

function buildSystem(skill) {
  // Use the skill's own instructions as the system prompt — exactly what the
  // playground does. This keeps scheduled output identical to interactive runs.
  return skill.instructions || skill.description || ('You are running the ' + skill.title + ' skill.');
}

async function runReport(r, date) {
  const skill = skillOf(r.skill);
  if (!skill) { console.error(`  ! skill not found: ${r.skill} (report ${r.id})`); return null; }
  const userMessage = (r.inputs || []).map((v, i) => `Input ${i + 1}:\n${v}`).join('\n\n');
  if (has('dry-run')) { console.log(`  · [dry-run] would run "${skill.title}" for ${r.id}`); return null; }
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) { console.error('  ! ANTHROPIC_API_KEY not set'); process.exit(1); }
  const out = await complete({
    apiKey: key,
    model: r.model || 'claude-sonnet-4-6',
    system: buildSystem(skill),
    messages: [{ role: 'user', content: userMessage }],
    maxTokens: 4096,
  });
  const stamp = date.toISOString().slice(0, 10);
  const dir = join(root, 'docs', 'reports', 'scheduled');
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const file = join(dir, `${r.id}-${stamp}.md`);
  const header = `---\nreport: ${r.id}\ntitle: ${r.title || r.id}\nskill: ${r.skill}\ngenerated: ${date.toISOString()}\n---\n\n# ${r.title || r.id}\n\n> Generated by the ${skill.title} skill on ${stamp}. Review before sending.\n\n`;
  writeFileSync(file, header + out.trim() + '\n');
  console.log(`  ✓ wrote docs/reports/scheduled/${r.id}-${stamp}.md`);
  return file;
}

const now = new Date();
const only = arg('id');
const reports = (cfg.reports || []).filter((r) => (only ? r.id === only : true));
const due = reports.filter((r) => has('force') || only || isDue(r, now));

console.log(`Scheduled reports · ${now.toISOString().slice(0, 10)} · ${due.length} due of ${reports.length}`);
if (!due.length) { console.log('Nothing due today.'); process.exit(0); }

let wrote = 0;
for (const r of due) {
  console.log(`- ${r.id} (${r.cadence})`);
  const f = await runReport(r, now);
  if (f) wrote++;
}
console.log(`Done. ${wrote} report(s) written.`);
